---
name: IPC-SRLock
version: 0.2.100
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Set/reset locking semantics to single thread processes
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::MakeMaker: 6.42
  version: 0.74
requires:
  Cache::Memcached: 1.24
  Class::Accessor::Fast: 0.31
  Class::Inspector: 1.18
  Class::Null: 1.09
  Data::Serializer: 0.46
  Date::Format: 2.22
  Exception::Class: 1.23
  IO::AtomicFile: 2.110
  IO::File: 1.14
  IPC::ShareLite: 0.13
  IPC::SysV: 1.04
  List::Util: 1.19
  Storable: 2.15
  Time::Elapsed: 0.10
  Time::HiRes: 1.9711
  parent: 0.221
  perl: 5.008
  version: 0.74
build_requires:
  Test::Harness: 2.64
  Test::More: 0.74
  Test::Pod: 1.14
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: 0.2.100
  IPC::SRLock::ExceptionClass:
    file: lib/IPC/SRLock/ExceptionClass.pm
    version: 0.2.96
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: 0.2.94
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: 0.2.94
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: 0.2.100
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
