---
abstract: 'Set/reset locking semantics to single thread processes'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  File::DataClass: v0.20.0
  Test::More: 0.74
configure_requires:
  Module::Build: 0.38
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-SRLock
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: v0.11.11
  IPC::SRLock::Base:
    file: lib/IPC/SRLock/Base.pm
    version: v0.11.10
  IPC::SRLock::Exception:
    file: lib/IPC/SRLock/Exception.pm
    version: v0.11.9
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: v0.11.6
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: v0.11.0
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: v0.11.0
recommends:
  Cache::Memcached: 1.24
requires:
  Class::Null: 1.09
  Date::Format: 2.22
  File::DataClass: v0.20.0
  IPC::ShareLite: 0.17
  Moose: 2.0402
  MooseX::Types: 0.25
  MooseX::Types::Common: 0.001008
  MooseX::Types::LoadableClass: 0.007
  Storable: 2.39
  Time::Elapsed: 0.1
  Time::HiRes: 1.9711
  Try::Tiny: 0.06
  Unexpected: v0.1.0
  parent: 0.221
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-SRLock
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.11.11
