---
abstract: 'Set/reset locking semantics to single thread processes'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Exception::Class: 1.23
  List::Util: 1.19
  Test::More: 0.74
configure_requires:
  Module::Build: 0.32
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-SRLock
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: v0.6.174
  IPC::SRLock::Exception:
    file: lib/IPC/SRLock/Exception.pm
    version: v0.6.164
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: v0.6.164
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: v0.6.164
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: v0.6.164
requires:
  Cache::Memcached: 1.24
  Class::Accessor::Fast: 0.31
  Class::MOP: 0.84
  Class::Null: 1.09
  Data::Serializer: 0.46
  Date::Format: 2.22
  Exception::Class: 1.23
  IO::AtomicFile: 2.11
  IO::File: 1.14
  IPC::ShareLite: 0.17
  List::Util: 1.19
  MRO::Compat: 0.11
  Storable: 2.15
  Time::Elapsed: 0.1
  Time::HiRes: 1.9711
  Try::Tiny: 0.06
  parent: 0.221
  perl: 5.008
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-SRLock
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.6.174
