---
name: IPC-SRLock
version: 0.1.23
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Set/reset locking semantics to single thread processes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cache::Memcached: 1.24
  Class::Accessor::Fast: 0.31
  Class::Inspector: 1.18
  Class::Null: 1.09
  Date::Format: 2.22
  Exception::Class: 1.23
  IO::AtomicFile: 2.110
  IO::File: 1.14
  IPC::SysV: 1.04
  List::Util: 1.19
  NEXT: 0.60
  Readonly: 1.03
  Time::Elapsed: 0.10
  Time::HiRes: 1.9711
  XML::Simple: 2.14
  perl: 5.8
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: 0.1.23
  IPC::SRLock::ExceptionClass:
    file: lib/IPC/SRLock/ExceptionClass.pm
    version: 0.1.23
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: 0.1.21
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: 0.1.22
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: 0.1.22
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
