---
abstract: 'Set/reset locking semantics to single thread processes'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  File::DataClass: v0.22.0
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-SRLock
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: v0.12.7
  IPC::SRLock::Base:
    file: lib/IPC/SRLock/Base.pm
    version: v0.12.1
  IPC::SRLock::Exception:
    file: lib/IPC/SRLock/Exception.pm
    version: v0.12.1
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: v0.12.1
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: v0.12.1
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: v0.12.1
recommends:
  Cache::Memcached: 1.24
requires:
  Class::Null: 1.09
  Date::Format: 2.24
  File::DataClass: v0.22.0
  IPC::ShareLite: 0.17
  Moo: 1.002
  Time::Elapsed: 0.29
  Try::Tiny: 0.09
  Type::Tiny: 0.012
  Unexpected: v0.4.0
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-SRLock
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.12.7
