---
abstract: 'Set/reset locking semantics to single thread processes'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  File::DataClass: v0.52.0
  Module::Build: '0.4202'
  Test::Requires: '0.06'
  version: '0.88'
configure_requires:
  Module::Build: '0.4202'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-SRLock
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  IPC::SRLock:
    file: lib/IPC/SRLock.pm
    version: v0.24.1
  IPC::SRLock::Base:
    file: lib/IPC/SRLock/Base.pm
    version: v0.24.1
  IPC::SRLock::Fcntl:
    file: lib/IPC/SRLock/Fcntl.pm
    version: v0.24.1
  IPC::SRLock::Memcached:
    file: lib/IPC/SRLock/Memcached.pm
    version: v0.24.1
  IPC::SRLock::Sysv:
    file: lib/IPC/SRLock/Sysv.pm
    version: v0.24.1
recommends:
  Cache::Memcached: '1.24'
requires:
  Class::Null: '1.09'
  Date::Format: '2.24'
  File::DataClass: v0.52.0
  IPC::ShareLite: '0.17'
  Moo: '1.006000'
  Time::Elapsed: '0.31'
  Try::Tiny: '0.22'
  Type::Tiny: '1.000002'
  namespace::autoclean: '0.19'
  perl: '5.010001'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-SRLock
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.24.1
